// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import <Foundation/Foundation.h>

extern const struct R {
    struct AssetsAssets {
        /// addPhoto
        __unsafe_unretained NSString *addPhoto;
        /// AppIcon
        __unsafe_unretained NSString *app;
        /// backArrow
        __unsafe_unretained NSString *backArrow;
        /// backBtn
        __unsafe_unretained NSString *backBtn;
        /// birthdayIcon
        __unsafe_unretained NSString *birthday;
        /// blueRounded
        __unsafe_unretained NSString *blueRounded;
        /// bottomOverlay
        __unsafe_unretained NSString *bottomOverlay;
        /// chat
        __unsafe_unretained NSString *chat;
        /// dislikePhoto
        __unsafe_unretained NSString *dislikePhoto;
        /// emptyImage
        __unsafe_unretained NSString *empty;
        /// Faves
        __unsafe_unretained NSString *faves;
        /// food
        __unsafe_unretained NSString *favesFood;
        /// music
        __unsafe_unretained NSString *favesMusic;
        /// sport
        __unsafe_unretained NSString *favesSport;
        /// travel
        __unsafe_unretained NSString *favesTravel;
        /// fbIcon
        __unsafe_unretained NSString *fb;
        /// fbBtn
        __unsafe_unretained NSString *fbBtn;
        /// FlirtLogo
        __unsafe_unretained NSString *flirtLogo;
        /// forwardArrow
        __unsafe_unretained NSString *forwardArrow;
        /// girlIcon
        __unsafe_unretained NSString *girl;
        /// girlIconActive
        __unsafe_unretained NSString *girlActive;
        /// ic_man_placeholder_300dp
        __unsafe_unretained NSString *icManPlaceholder300dp;
        /// ic_woman_placeholder_300dp
        __unsafe_unretained NSString *icWomanPlaceholder300dp;
        /// leftSplashBtn
        __unsafe_unretained NSString *leftSplashBtn;
        /// likePhoto
        __unsafe_unretained NSString *likePhoto;
        /// locationIcon2
        __unsafe_unretained NSString *location2;
        /// mail
        __unsafe_unretained NSString *mail;
        /// manIcon
        __unsafe_unretained NSString *man;
        /// manInactive
        __unsafe_unretained NSString *manInactive;
        /// Menu
        __unsafe_unretained NSString *menu;
        /// menuAbout
        __unsafe_unretained NSString *menuAbout;
        /// menuAvatar
        __unsafe_unretained NSString *menuAvatar;
        /// menuBg
        __unsafe_unretained NSString *menuBg;
        /// menuBlocked
        __unsafe_unretained NSString *menuBlocked;
        /// menuBtn
        __unsafe_unretained NSString *menuBtn;
        /// menuFave
        __unsafe_unretained NSString *menuFave;
        /// menuFeedback
        __unsafe_unretained NSString *menuFeedback;
        /// menuLine
        __unsafe_unretained NSString *menuLine;
        /// menuLogout
        __unsafe_unretained NSString *menuLogout;
        /// menuMeetings
        __unsafe_unretained NSString *menuMeetings;
        /// menuMessages
        __unsafe_unretained NSString *menuMessages;
        /// menuOnline
        __unsafe_unretained NSString *menuOnline;
        /// menuRadar
        __unsafe_unretained NSString *menuRadar;
        /// menuSearch
        __unsafe_unretained NSString *menuSearch;
        /// menuSelectedBtn
        __unsafe_unretained NSString *menuSelectedBtn;
        /// menuSettings
        __unsafe_unretained NSString *menuSettings;
        /// menuSettings-1
        __unsafe_unretained NSString *menuSettings1;
        /// menuSexy
        __unsafe_unretained NSString *menuSexy;
        /// menuVisitors
        __unsafe_unretained NSString *menuVisitors;
        /// Messages
        __unsafe_unretained NSString *messages;
        /// Chat
        __unsafe_unretained NSString *messagesChat;
        /// chatAvatar
        __unsafe_unretained NSString *messagesChatAvatar;
        /// chatBubbleBlue
        __unsafe_unretained NSString *messagesChatBubbleBlue;
        /// chatPlus
        __unsafe_unretained NSString *messagesChatPlus;
        /// chatSendBtn
        __unsafe_unretained NSString *messagesChatSendBtn;
        /// chatSendedIcon
        __unsafe_unretained NSString *messagesChatSended;
        /// deleteImage
        __unsafe_unretained NSString *messagesDelete;
        /// inboxArchiveIcon
        __unsafe_unretained NSString *messagesInboxArchive;
        /// inboxCellArchive
        __unsafe_unretained NSString *messagesInboxCellArchive;
        /// inboxCellAvatar
        __unsafe_unretained NSString *messagesInboxCellAvatar;
        /// inboxCellCircle
        __unsafe_unretained NSString *messagesInboxCellCircle;
        /// inboxCellTrash
        __unsafe_unretained NSString *messagesInboxCellTrash;
        /// inboxTrashIcon
        __unsafe_unretained NSString *messagesInboxTrash;
        /// newLoginIcon
        __unsafe_unretained NSString *newLogin;
        /// newLoginBg
        __unsafe_unretained NSString *newLoginBg;
        /// Online
        __unsafe_unretained NSString *online;
        /// onlineFilter
        __unsafe_unretained NSString *onlineFilter;
        /// onlineFilterBg
        __unsafe_unretained NSString *onlineFilterBg;
        /// onlineGirl
        __unsafe_unretained NSString *onlineGirl;
        /// onlinePressedFilter
        __unsafe_unretained NSString *onlinePressedFilter;
        /// onlineSearch
        __unsafe_unretained NSString *onlineSearch;
        /// onlineSearchOnField
        __unsafe_unretained NSString *onlineSearchField;
        /// onlineTrash
        __unsafe_unretained NSString *onlineTrash;
        /// password
        __unsafe_unretained NSString *password;
        /// PhotoMenu
        __unsafe_unretained NSString *photoMenu;
        /// menuOpenedBlock
        __unsafe_unretained NSString *photoMenuOpenedBlock;
        /// menuOpenedBlockSelected
        __unsafe_unretained NSString *photoMenuOpenedBlockSelected;
        /// menuOpenedDots
        __unsafe_unretained NSString *photoMenuOpenedDots;
        /// menuOpenedReport
        __unsafe_unretained NSString *photoMenuOpenedReport;
        /// menuOpenedReportSelected
        __unsafe_unretained NSString *photoMenuOpenedReportSelected;
        /// menuOpenedStar
        __unsafe_unretained NSString *photoMenuOpenedStar;
        /// menuOpenedStarSelected
        __unsafe_unretained NSString *photoMenuOpenedStarSelected;
        /// Profile
        __unsafe_unretained NSString *profile;
        /// profileAboutBtn
        __unsafe_unretained NSString *profileAboutBtn;
        /// profileAddAlertImg
        __unsafe_unretained NSString *profileAddAlertImg;
        /// profileAddPhotoBg
        __unsafe_unretained NSString *profileAddPhotoBg;
        /// profileBody
        __unsafe_unretained NSString *profileBody;
        /// profileBubble
        __unsafe_unretained NSString *profileBubble;
        /// profileClose
        __unsafe_unretained NSString *profileClose;
        /// descriptionImage
        __unsafe_unretained NSString *profileDescription;
        /// profileDots
        __unsafe_unretained NSString *profileDots;
        /// profileEditBtn
        __unsafe_unretained NSString *profileEditBtn;
        /// profileEducation
        __unsafe_unretained NSString *profileEducation;
        /// profileEmptyImage
        __unsafe_unretained NSString *profileEmpty;
        /// profileEye
        __unsafe_unretained NSString *profileEye;
        /// profileGetPhoto
        __unsafe_unretained NSString *profileGetPhoto;
        /// profileHair
        __unsafe_unretained NSString *profileHair;
        /// profileHeight
        __unsafe_unretained NSString *profileHeight;
        /// profileLanguage
        __unsafe_unretained NSString *profileLanguage;
        /// profileLocation
        __unsafe_unretained NSString *profileLocation;
        /// photosBg
        __unsafe_unretained NSString *profilePhotosBg;
        /// privacyImage
        __unsafe_unretained NSString *profilePrivacy;
        /// sandclock
        __unsafe_unretained NSString *profileSandclock;
        /// selectedLine
        __unsafe_unretained NSString *profileSelectedLine;
        /// profileSettings
        __unsafe_unretained NSString *profileSettings;
        /// profileSex
        __unsafe_unretained NSString *profileSex;
        /// profileUploadBtn
        __unsafe_unretained NSString *profileUploadBtn;
        /// Radar
        __unsafe_unretained NSString *radar;
        /// radarCircle
        __unsafe_unretained NSString *radarCircle;
        /// radarEl1
        __unsafe_unretained NSString *radarEl1;
        /// radarEl2
        __unsafe_unretained NSString *radarEl2;
        /// radarLine
        __unsafe_unretained NSString *radarLine;
        /// locationIcon
        __unsafe_unretained NSString *radarLocation;
        /// locationPointer
        __unsafe_unretained NSString *radarLocationPointer;
        /// RangeSelector
        __unsafe_unretained NSString *rangeSelector;
        /// rangeSelectorDot
        __unsafe_unretained NSString *rangeSelectorDot;
        /// rangeSelectorLine
        __unsafe_unretained NSString *rangeSelectorLine;
        /// rangeSelectorSelectedLine
        __unsafe_unretained NSString *rangeSelectorSelectedLine;
        /// rightSignBtn
        __unsafe_unretained NSString *rightSignBtn;
        /// roundedWhite
        __unsafe_unretained NSString *roundedWhite;
        /// sexualityIcon
        __unsafe_unretained NSString *sexuality;
        /// sexyNBtn
        __unsafe_unretained NSString *sexyNBtn;
        /// sexyNBtn_sel
        __unsafe_unretained NSString *sexyNBtnSel;
        /// SexyOrNot
        __unsafe_unretained NSString *sexyOrNot;
        /// emptyStar
        __unsafe_unretained NSString *sexyOrNotEmptyStar;
        /// fullStar
        __unsafe_unretained NSString *sexyOrNotFullStar;
        /// nextIcon
        __unsafe_unretained NSString *sexyOrNotNext;
        /// previousIcon
        __unsafe_unretained NSString *sexyOrNotPrevious;
        /// whiteOval
        __unsafe_unretained NSString *sexyOrNotWhiteOval;
        /// signupAddPhoto
        __unsafe_unretained NSString *signupAddPhoto;
        /// signupBirthday
        __unsafe_unretained NSString *signupBirthday;
        /// signupLocation
        __unsafe_unretained NSString *signupLocation;
        /// signupMail
        __unsafe_unretained NSString *signupMail;
        /// signupName
        __unsafe_unretained NSString *signupName;
        /// signupPass
        __unsafe_unretained NSString *signupPass;
        /// splashBg
        __unsafe_unretained NSString *splashBg;
        /// topOverlay
        __unsafe_unretained NSString *topOverlay;
        /// usernameIcon
        __unsafe_unretained NSString *username;
    } AssetsAssets;
} R;
